# Generated by Django 4.1 on 2022-09-02 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
